In [1]:
import configparser
import hashlib
import itertools  # for reading the parameters file
import sys  # for system errors and printouts
from pathlib import Path  # for paths of files
import os  # for reading the input data
import time  # for timing
import pandas as pd
import random
import numpy as np

In [2]:
# Global parameters
parameter_file = 'default_parameters.ini'  # the main parameters file
# the main path where all the data directories are
data_main_directory = Path('data')
# dictionary that holds the input parameters, key = parameter name, value = value
parameters_dictionary = dict()
# dictionary of the input documents, key = document id, value = the document
document_list = dict()


# DO NOT CHANGE THIS METHOD
# Reads the parameters of the project from the parameter file 'file'
# and stores them to the parameter dictionary 'parameters_dictionary'
def read_parameters():
    config = configparser.ConfigParser()
    config.read(parameter_file)
    for section in config.sections():
        for key in config[section]:
            if key == 'data':
                parameters_dictionary[key] = config[section][key]
            elif key == 'naive':
                parameters_dictionary[key] = bool(config[section][key])
            elif key == 't':
                parameters_dictionary[key] = float(config[section][key])
            else:
                parameters_dictionary[key] = int(config[section][key])


# DO NOT CHANGE THIS METHOD
# Reads all the documents in the 'data_path' and stores them in the dictionary 'document_list'
def read_data(data_path):
    for (root, dirs, file) in os.walk(data_path):
        for f in file:
            file_path = data_path / f
            doc = open(file_path).read().strip().replace('\n', ' ')
            file_id = int(file_path.stem)
            document_list[file_id] = doc


# DO NOT CHANGE THIS METHOD
# Calculates the Jaccard Similarity between two documents represented as sets
def jaccard(doc1, doc2):
    return len(doc1.intersection(doc2)) / float(len(doc1.union(doc2)))


# DO NOT CHANGE THIS METHOD
# Define a function to map a 2D matrix coordinate into a 1D index.
def get_triangle_index(i, j, length):
    if i == j:  # that's an error.
        sys.stderr.write("Can't access triangle matrix with i == j")
        sys.exit(1)
    if j < i:  # just swap the values.
        temp = i
        i = j
        j = temp

    # Calculate the index within the triangular array. Taken from pg. 211 of:
    # http://infolab.stanford.edu/~ullman/mmds/ch6.pdf
    # adapted for a 0-based index.
    k = int(i * (length - (i + 1) / 2.0) + j - i) - 1

    return k


# DO NOT CHANGE THIS METHOD
# Calculates the similarities of all the combinations of documents and returns the similarity triangular matrix
def naive():
    docs_Sets = []  # holds the set of words of each document

    for doc in document_list.values():
        docs_Sets.append(set(doc.split()))

    # Using triangular array to store the similarities, avoiding half size and similarities of i==j
    num_elems = int(len(docs_Sets) * (len(docs_Sets) - 1) / 2)
    similarity_matrix = [0 for x in range(num_elems)]
    for i in range(len(docs_Sets)):
        for j in range(i + 1, len(docs_Sets)):
            similarity_matrix[get_triangle_index(i, j, len(docs_Sets))] = jaccard(
                docs_Sets[i], docs_Sets[j])

    return similarity_matrix


In [3]:
read_parameters()
#print(parameters_dictionary['data'])

# Reading the data
print("Data reading...")
data_folder = data_main_directory / parameters_dictionary['data']
t0 = time.time()
read_data(data_folder)
document_list = {k: document_list[k] for k in sorted(document_list)}
t1 = time.time()
print(len(document_list), "documents were read in", t1 - t0, "sec\n")

# Naive
naive_similarity_matrix = []
if parameters_dictionary['naive']:
    print("Starting to calculate the similarities of documents...")
    t2 = time.time()
    naive_similarity_matrix = naive()
    t3 = time.time()
    print("Calculating the similarities of", len(naive_similarity_matrix),
            "combinations of documents took", t3 - t2, "sec\n")


Data reading...
400 documents were read in 0.14757037162780762 sec

Starting to calculate the similarities of documents...
Calculating the similarities of 79800 combinations of documents took 1.9797072410583496 sec



In [4]:
def k_shingles():
    docs_k_shingles = []  # holds the k-shingles of each document
    # implement your code here

    # Get the value k from the parameters dictionary
    k = parameters_dictionary.get("k")

    for key in document_list:
        document = document_list[key]
        words = document.split()

        shingles_in_doc = []
        for i in range(len(words)-k+1):

            shingle = words[i:i + k]

            shingle = ' '.join(shingle)

            if shingle not in shingles_in_doc:
                shingles_in_doc.append(shingle)

        docs_k_shingles.append(shingles_in_doc)

    return docs_k_shingles


docs_k_shingles = k_shingles()

In [5]:
# METHOD FOR TASK 2
# Creates a signatures set of the documents from the k-shingles list
def signature_set(shingles):
    # docs_sig_sets = []
    # print(shingles)

    docs_signature_sets = []
    # print("len", len(document_list))
    for key in range(0, len(document_list)):
        # print("key ", key)
        # print(document_list[key])
        # print(len(document_list))

        shingle = shingles[key]
        # print("shingle", shingle)
        signature_set_shingle = set()

        # print(type(document_list))

        # for shingle in document_list
        # document = document_list[key+1]

        # print("doc: ",document)
        for i in range(len(shingles[key])):
            hash_val = hash(shingle[i])
            # print(hash_val)
            if hash_val not in signature_set_shingle:
                signature_set_shingle.add(hash_val)

            # shing = shingles[key][i]
            # print(shing in document)
        # print(signature_set_shingle)
        docs_signature_sets.append(signature_set_shingle)
    return docs_signature_sets

docs_signature_sets = signature_set(docs_k_shingles)

In [33]:


# Sjekker hvis et tall er et prim tall
def is_prime(n):
    if n == 2 or n == 3:
        return True
    if n < 2 or n % 2 == 0:
        return False
    if n < 9:
        return True
    if n % 3 == 0:
        return False
    r = int(n**0.5)
    # since all primes > 3 are of the form 6n ± 1
    # start with f=5 (which is prime)
    # and test f, f+2 for being prime
    # then loop by 6.
    f = 5
    while f <= r:
        if n % f == 0:
            return False
        if n % (f+2) == 0:
            return False
        f += 6
    return True

random.seed(11)

def minHash(document_vector):
    num_permutations = parameters_dictionary.get("permutations")
    num_documents = len(document_list)

    # Nye
    signatures = np.full((num_documents, num_permutations), np.inf)
    #Gammel 
    #signatures = np.full((num_permutations,num_documents), np.inf)
    
    count = 0
    perms = 0
    docies = 0

    #Nye
    for i in range(num_documents):
    #Gammel
    #for i in range(num_permutations):
        a = random.randint(1, 400)
        b = random.randint(1, 400)
        cont = True
        while cont:
            # Generate a random number in the range [lower_bound, upper_bound]
            p = random.randint(400, 1000)

            # Check if the number is prime
            if is_prime(p):
                cont = False
        perms += 1
        #nye
        for j in range(num_permutations):
        #gammel
        #for j in range(num_documents):
            docies += 1
            localcount = 1
            for sig in document_vector[j]:

                hash_value = (a * sig + b) % p
                count += 1
                localcount += 1

                if hash_value < signatures[i][j]:
                    signatures[i][j] = hash_value
    return signatures

signatures = minHash(docs_signature_sets)


In [7]:
#print(signaturesGammel)
#print(signaturesNy)

In [8]:
""" 
#print(signaturesNy)
templis =[]
tempcols = []
for i in signaturesNy:
    templis.append(i[0])
for j in signaturesGammel:
    tempcols.append(j[0])
print(templis)
print(tempcols)
"""

' \n#print(signaturesNy)\ntemplis =[]\ntempcols = []\nfor i in signaturesNy:\n    templis.append(i[0])\nfor j in signaturesGammel:\n    tempcols.append(j[0])\nprint(templis)\nprint(tempcols)\n'

[0.0, 5.0, 1.0, 1.0, 1.0, 1.0, 4.0, 1.0, 3.0, 1.0, 4.0, 0.0, 0.0, 0.0, 0.0, 1.0, 7.0, 0.0, 0.0, 0.0]
[0.0, 5.0, 1.0, 1.0, 1.0, 1.0, 4.0, 1.0, 3.0, 1.0]


In [37]:
# METHOD FOR TASK 4
# Hashes the MinHash Signature Matrix into buckets and find candidate similar documents
def lsh(m_matrix):

    candidates = []  # list of candidate sets of documents for checking similarity
    print(m_matrix.T)
    #m_matrix = m_matrix.T
    # implement your code here
    buckets = parameters_dictionary.get("buckets")
    # permutations = parameters_dictionary.get("permutations")
    # bands = len(m_matrix[0])/buckets
    # print(bands)
    # for signature in m_matrix:
    bucket_dict = {}
    for i in range(buckets):
        bucket_dict[i] = set()

    print("shape ",m_matrix.shape[0])
    # Hash each column of the signature matrix into a bucket
    for j in range(m_matrix.shape[0]):
        #hash_val = hash(tuple(m_matrix[:, j]))
        hash_val = hash(tuple(m_matrix[j, :]))
        bucket_idx = hash_val % buckets
        bucket_dict[bucket_idx].add(j)

    # Find candidate similar documents from the buckets
    candidates = set()
    for bucket in bucket_dict.values():
        print(len(bucket))
        if len(bucket) > 1:
            pairs = list(itertools.combinations(bucket, 2))
            print(pairs)
            candidates.update(pairs)

    return candidates

In [38]:
candidates = lsh(signatures)

[[ 0.  0.  0. ...  3.  3.  0.]
 [ 1.  0.  2. ...  0.  2.  1.]
 [ 7.  5.  5. ...  0.  0.  2.]
 ...
 [ 0.  1.  0. ...  1.  0.  3.]
 [ 7. 10.  1. ...  1.  1.  1.]
 [ 1.  0.  0. ...  0.  1.  3.]]
shape  400
41
[(128, 2), (128, 389), (128, 134), (128, 391), (128, 142), (128, 15), (128, 270), (128, 398), (128, 148), (128, 152), (128, 154), (128, 27), (128, 283), (128, 285), (128, 160), (128, 46), (128, 176), (128, 180), (128, 311), (128, 186), (128, 59), (128, 197), (128, 326), (128, 330), (128, 75), (128, 203), (128, 79), (128, 337), (128, 210), (128, 213), (128, 90), (128, 219), (128, 220), (128, 100), (128, 229), (128, 104), (128, 239), (128, 241), (128, 248), (128, 121), (2, 389), (2, 134), (2, 391), (2, 142), (2, 15), (2, 270), (2, 398), (2, 148), (2, 152), (2, 154), (2, 27), (2, 283), (2, 285), (2, 160), (2, 46), (2, 176), (2, 180), (2, 311), (2, 186), (2, 59), (2, 197), (2, 326), (2, 330), (2, 75), (2, 203), (2, 79), (2, 337), (2, 210), (2, 213), (2, 90), (2, 219), (2, 220), (2, 100),

In [40]:
#print(type(candidates))
c = candidates
#c = list(candidates)[0]
print(candidates)
#print(signatures)

    #print(i)

    #print(list(candidates)[i])


[[ 0.  1.  7. ...  0.  7.  1.]
 [ 0.  0.  5. ...  1. 10.  0.]
 [ 0.  2.  5. ...  0.  1.  0.]
 ...
 [ 3.  0.  0. ...  1.  1.  0.]
 [ 3.  2.  0. ...  0.  1.  1.]
 [ 0.  1.  2. ...  3.  1.  3.]]


In [12]:
""" similarity(d1, d2) = #(hi(d1) == hi(d2))
permutations
"""
# METHOD FOR TASK 5
# Calculates the similarities of the candidate documents
def candidates_similarities(candidate_docs, min_hash_matrix):
    similarity_matrix = []
    print("candidates ", candidate_docs)
    print("\n\n Min hash", min_hash_matrix)

    # implement your code here
    return similarity_matrix
